import {
  Eye,
  EyeOff,
  LayoutDashboard,
  Users,
  UserCog,
  FileText,
  Settings,
  LogOut,
  User,
  Search,
  Bell,
  MessageCircleQuestionMark,
  ChevronDown,
  MoveRight,
  MessageSquareText,
  Phone,
  Drill,
  ReceiptText,
} from "lucide-react";

export const ICONS = {
  eye_on: Eye,
  eye_off: EyeOff,
  dashboard: LayoutDashboard,
  users: Users,
  user_cog: UserCog,
  file_text: FileText,
  settings: Settings,
  logout: LogOut,
  user: User,
  search: Search,
  bell: Bell,
  help: MessageCircleQuestionMark,
  drop_down: ChevronDown,
  move_right: MoveRight,
  message: MessageSquareText,
  phone: Phone,
  drill: Drill,
  receipt: ReceiptText,
};
